"""table 2 creation

Revision ID: 828d3c51cef6
Revises: cadd3db2e3f0
Create Date: 2023-07-03 03:15:02.446556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828d3c51cef6'
down_revision = 'cadd3db2e3f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
