"""table 3 creation

Revision ID: dcb76132cecb
Revises: 828d3c51cef6
Create Date: 2023-07-03 03:16:47.267988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb76132cecb'
down_revision = '828d3c51cef6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
